/*
System.Boolean
System.Double
System.String
System.Int32
System.Int64
System.Single
System.Double
System.Object
System.DateTime
UnityScript.Lang.Array
Boo.Lang.ICallable
*/
print(typeof(boolean));
print(typeof(Number));
print(typeof(String));
print(typeof(int));
print(typeof(long));
print(typeof(float));
print(typeof(double));
print(typeof(Object));
print(typeof(Date));
print(typeof(Array));
print(typeof(Function));
