#region license
// Copyright (c) 2003, 2004, 2005 Rodrigo B. de Oliveira (rbo@acm.org)
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
// 
//     * Redistributions of source code must retain the above copyright notice,
//     this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//     * Neither the name of Rodrigo B. de Oliveira nor the names of its
//     contributors may be used to endorse or promote products derived from this
//     software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#endregion

//
// DO NOT EDIT THIS FILE!
//
// This file was generated automatically by astgen.boo.
//

namespace Boo.Lang.Compiler.Ast
{
	using System;
	using Boo.Lang;
	using Boo.Lang.Compiler.Ast;
	
	[Serializable]
	[EnumeratorItemType(typeof(Boo.Lang.Compiler.Ast.Slice))]
	public class  SliceCollectionImpl : NodeCollection
	{
		public static SliceCollection FromArray(params Boo.Lang.Compiler.Ast.Slice[] items)
		{
			SliceCollection collection = new SliceCollection();
			collection.Extend(items);
			return collection;
		}
		
		protected  SliceCollectionImpl()
		{
		}

		protected  SliceCollectionImpl(Boo.Lang.Compiler.Ast.Node parent) : base(parent)
		{
		}

		public Boo.Lang.Compiler.Ast.SliceCollection PopRange(int begin)
		{
			Boo.Lang.Compiler.Ast.SliceCollection range = new Boo.Lang.Compiler.Ast.SliceCollection(_parent);
			range.InnerList.Extend(InternalPopRange(begin));
			return range;
		}
		
		public Boo.Lang.Compiler.Ast.Slice this[int index]
		{
			get { return (Boo.Lang.Compiler.Ast.Slice)InnerList[index]; }
			set { ReplaceNodeAt(index, value); }
		}
		
		public void Add(Boo.Lang.Compiler.Ast.Slice item)
		{
			AddImpl(item);
		}
		
		public void Insert(int index, Boo.Lang.Compiler.Ast.Slice item)
		{
			InsertImpl(index, item);
		}
		
		public bool Replace(Boo.Lang.Compiler.Ast.Slice existingNode, Boo.Lang.Compiler.Ast.Slice newNode)
		{
			return ReplaceImpl(existingNode, newNode);
		}
		
		public void ReplaceAt(int index, Boo.Lang.Compiler.Ast.Slice newNode)
		{
			ReplaceNodeAt(index, newNode);
		}
		
		public Boo.Lang.Compiler.Ast.Slice[] ToArray()
		{
			return (Boo.Lang.Compiler.Ast.Slice[])ToArray(typeof(Boo.Lang.Compiler.Ast.Slice));
		}
		
		public Boo.Lang.Compiler.Ast.Slice[] ToReverseArray()
		{
			return (Boo.Lang.Compiler.Ast.Slice[])ToReverseArray(typeof(Boo.Lang.Compiler.Ast.Slice));
		}
	}
}

